name: Flutter CI Stable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter (STABLE FIXED)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4
          channel: stable

      - name: Clean
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
